language: python3
jdk:
  - openjdk8
  - openjdk11
python:
  "3.8"
services:
  - docker
before_install:
  - chmod +x ./travis.sh
    #- apt-cache search python
    #- sudo apt-get install python3.6
script:
  - cd dwh; ./validate_indicators.sh

