jobs:
  include:
    - language: java
      jdk:
        - openjdk8
        - openjdk11  # TODO: Check why this is not triggered!
      services:
        - docker
      before_install:
        - sudo apt install jq
        - chmod +x ./e2e-tests/batch-mode-tests.sh
      script:
        - mvn clean install
        - ./e2e-tests/batch-mode-tests.sh

    - language: python
      python:  "3.8"
      script:
        - cd dwh; ./validate_indicators.sh